services:
  db:
    image: postgres:18.2
    container_name: postgres_db
    restart: unless-stopped
    environment:
      # CONFIGURAÇÕES DO POSTGRESQL
      POSTGRES_DB: colaai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senhazona
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:9.12.0
    container_name: pgadmin
    restart: unless-stopped
    environment:
      # CONFIGURAÇÕES DO PGADMIN
      PGADMIN_DEFAULT_EMAIL: admin@colaai.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      TZ: America/Sao_Paulo
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      org.springframework.boot.ignore: true
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin_data: