-- TABELA: usuarios
CREATE TABLE "usuarios" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email"        VARCHAR(255) NOT NULL,
  "senhaHash"    VARCHAR(255) NOT NULL,
  "dataCriacao"  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza" TIMESTAMP NULL,
  CONSTRAINT "usuarios_email_uk" UNIQUE ("email")
);

-- TABELA: papeis
CREATE TABLE "papeis" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "papel"        VARCHAR(30) NOT NULL,
  "dataCriacao"  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza" TIMESTAMP NULL,
  CONSTRAINT "papeis_papel_uk" UNIQUE ("papel")
);

-- TABELA: papelUsuario (associação)
CREATE TABLE "papelUsuario" (
  "idUsuario"    INTEGER NOT NULL,
  "idPapel"      INTEGER NOT NULL,
  "dataCriacao"  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza" TIMESTAMP NULL,
  PRIMARY KEY ("idUsuario", "idPapel"),
  CONSTRAINT "papelUsuario_usuario_fk"
    FOREIGN KEY ("idUsuario") REFERENCES "usuarios" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "papelUsuario_papel_fk"
    FOREIGN KEY ("idPapel") REFERENCES "papeis" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "papelUsuario_idPapel_idx"   ON "papelUsuario" ("idPapel");
CREATE INDEX "papelUsuario_idUsuario_idx" ON "papelUsuario" ("idUsuario");

-- TABELA: cidades
CREATE TABLE "cidades" (
  "codIbge"     INTEGER NOT NULL PRIMARY KEY,
  "nome"        VARCHAR(120) NOT NULL,
  "uf"          VARCHAR(2) NOT NULL,
  "dataCriacao" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

-- TABELA: enderecos
CREATE TABLE "enderecos" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idCidade"     INTEGER NOT NULL,
  "cep"          VARCHAR(8) NULL,
  "logradouro"   VARCHAR(120) NULL,
  "bairro"       VARCHAR(100) NULL,
  "numero"       VARCHAR(20) NULL,
  "complemento"  VARCHAR(100) NULL,
  "dataCriacao"  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza" TIMESTAMP NULL,
  CONSTRAINT "enderecos_cidades_fk"
    FOREIGN KEY ("idCidade") REFERENCES "cidades" ("codIbge")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "enderecos_idCidade_idx" ON "enderecos" ("idCidade");

-- TABELA: categorias
CREATE TABLE "categorias" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome"         VARCHAR(60) NOT NULL,
  "slug"         VARCHAR(160) NOT NULL,
  "dataCriacao"  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "categorias_slug_uk" UNIQUE ("slug")
);

-- TABELA: eventos
CREATE TABLE "eventos" (
  "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idOrganizador" INTEGER NOT NULL,
  "status"        VARCHAR(20) NOT NULL,
  "nome"          VARCHAR(120) NOT NULL,
  "slug"          VARCHAR(160) NOT NULL,
  "imgCapa"       VARCHAR(255) NULL,
  "descricao"     TEXT NOT NULL,
  "idCategoria"   INTEGER NOT NULL,
  "dataInicio"    TIMESTAMP NOT NULL,
  "dataFim"       TIMESTAMP NOT NULL,
  "idEndereco"    INTEGER NOT NULL,
  "localizacao"   VARCHAR(120) NULL,
  "regulamento"   VARCHAR(150) NULL,
  "dataCriacao"   TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza"  TIMESTAMP NULL,
  CONSTRAINT "eventos_slug_uk" UNIQUE ("slug"),
  CONSTRAINT "eventos_categoria_fk"
    FOREIGN KEY ("idCategoria") REFERENCES "categorias" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "eventos_endereco_fk"
    FOREIGN KEY ("idEndereco") REFERENCES "enderecos" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "eventos_organizador_fk"
    FOREIGN KEY ("idOrganizador") REFERENCES "usuarios" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "eventos_idCategoria_idx"   ON "eventos" ("idCategoria");
CREATE INDEX "eventos_idEndereco_idx"    ON "eventos" ("idEndereco");
CREATE INDEX "eventos_idOrganizador_idx" ON "eventos" ("idOrganizador");

-- TABELA: pessoas
CREATE TABLE "pessoas" (
  "id"             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuarioId"      INTEGER NOT NULL,
  "nome"           VARCHAR(100) NOT NULL,
  "apelido"        VARCHAR(100) NULL,
  "fotoPerfil"     VARCHAR(255) NULL,
  "cpfHash"        VARCHAR(64) NULL,
  "dataNascimento" DATE NULL,
  "telefone"       VARCHAR(11) NOT NULL,
  "pessoaEmerg"    VARCHAR(100) NULL,
  "contatoEmerg"   VARCHAR(11) NULL,
  "sexo"           CHAR(1) NOT NULL,
  "idEndereco"     INTEGER NOT NULL,
  "dataCriacao"    TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza"   TIMESTAMP NULL,
  CONSTRAINT "pessoas_cpfHash_uk" UNIQUE ("cpfHash"),
  CONSTRAINT "pessoas_usuarioId_uk" UNIQUE ("usuarioId"),
  CONSTRAINT "pessoas_endereco_fk"
    FOREIGN KEY ("idEndereco") REFERENCES "enderecos" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "pessoas_usuario_fk"
    FOREIGN KEY ("usuarioId") REFERENCES "usuarios" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "pessoas_idEndereco_idx" ON "pessoas" ("idEndereco");

-- TABELA: modalidades
CREATE TABLE "modalidades" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idEvento"     INTEGER NOT NULL,
  "nome"         VARCHAR(120) NOT NULL,
  "status"       VARCHAR(20) NOT NULL,
  "kmDistancia"  DOUBLE PRECISION NULL,
  "sexoPadrao"   CHAR(1) NULL,
  "dataCriacao"  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza" TIMESTAMP NULL,
  CONSTRAINT "modalidades_evento_fk"
    FOREIGN KEY ("idEvento") REFERENCES "eventos" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "modalidades_idEvento_idx" ON "modalidades" ("idEvento");

-- TABELA: ingressos
CREATE TABLE "ingressos" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idModalidade" INTEGER NOT NULL,
  "status"       VARCHAR(20) NOT NULL,
  "descricao"    TEXT NOT NULL,
  "quantidade"   INTEGER NULL,
  "preco"        NUMERIC(10,2) NOT NULL,
  "dataInicio"   TIMESTAMP NULL,
  "dataFim"      TIMESTAMP NULL,
  "idadeMin"     INTEGER NULL,
  "idadeMax"     INTEGER NULL,
  "sexo"         CHAR(1) NULL,
  "dataCriacao"  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza" TIMESTAMP NULL,
  CONSTRAINT "ingressos_modalidade_fk"
    FOREIGN KEY ("idModalidade") REFERENCES "modalidades" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "ingressos_idModalidade_idx" ON "ingressos" ("idModalidade");

-- TABELA: pedidos
CREATE TABLE "pedidos" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "compradorId"  INTEGER NOT NULL,
  "status"       VARCHAR(20) NOT NULL,
  "valorTotal"   NUMERIC(10,2) NOT NULL,
  "dataCriacao"  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza" TIMESTAMP NULL,
  CONSTRAINT "pedidos_comprador_fk"
    FOREIGN KEY ("compradorId") REFERENCES "usuarios" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "pedidos_compradorId_idx" ON "pedidos" ("compradorId");

-- TABELA: itensPedido
CREATE TABLE "itensPedido" (
  "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idPedido"      INTEGER NOT NULL,
  "idIngresso"    INTEGER NOT NULL,
  "quantidade"    INTEGER NOT NULL,
  "valorUnitario" NUMERIC(10,2) NOT NULL,
  CONSTRAINT "itensPedido_pedido_fk"
    FOREIGN KEY ("idPedido") REFERENCES "pedidos" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "itensPedido_ingresso_fk"
    FOREIGN KEY ("idIngresso") REFERENCES "ingressos" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "itensPedido_idIngresso_idx" ON "itensPedido" ("idIngresso");
CREATE INDEX "itensPedido_idPedido_idx"   ON "itensPedido" ("idPedido");

-- TABELA: equipes
CREATE TABLE "equipes" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idCriador"    INTEGER NOT NULL,
  "idEvento"     INTEGER NOT NULL,
  "nome"         VARCHAR(60) NOT NULL,
  "slug"         VARCHAR(160) NOT NULL,
  "dataCriacao"  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza" TIMESTAMP NULL,
  CONSTRAINT "equipes_criador_fk"
    FOREIGN KEY ("idCriador") REFERENCES "usuarios" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "equipes_evento_fk"
    FOREIGN KEY ("idEvento") REFERENCES "eventos" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "equipes_idCriador_idx" ON "equipes" ("idCriador");
CREATE INDEX "equipes_idEvento_idx"  ON "equipes" ("idEvento");

-- TABELA: inscricoes
CREATE TABLE "inscricoes" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idPessoa"     INTEGER NOT NULL,
  "idItemPedido" INTEGER NOT NULL,
  "idEquipe"     INTEGER NULL,
  "status"       VARCHAR(20) NOT NULL,
  "dataCriacao"  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualiza" TIMESTAMP NULL,
  CONSTRAINT "inscricoes_item_pedido_fk"
    FOREIGN KEY ("idItemPedido") REFERENCES "itensPedido" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "inscricoes_pessoa_fk"
    FOREIGN KEY ("idPessoa") REFERENCES "pessoas" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "inscricoes_equipe_fk"
    FOREIGN KEY ("idEquipe") REFERENCES "equipes" ("id")
    ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "inscricoes_idItemPedido_idx" ON "inscricoes" ("idItemPedido");
CREATE INDEX "inscricoes_idPessoa_idx"     ON "inscricoes" ("idPessoa");
CREATE INDEX "inscricoes_idEquipe_idx"     ON "inscricoes" ("idEquipe");
